language: ruby
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libpcap-dev

rvm:
  #- '1.8.7'
  - '1.9.3'

notifications:
  irc: "irc.freenode.org#msfnotify"

git:
  depth: 1
